apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  labels:
    name: cs-pvc
  namespace: csns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-xfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-deploy
  labels:
    name: cs-deploy
    app: codeserver
  namespace: csns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cs-po
      app: codeserver
  template:
    metadata:
      name: cs-po
      labels:
        app: codeserver
        name: cs-po
    spec:
      volumes:
        - name: workspace-vol
          persistentVolumeClaim:
            claimName: cs-pvc
      containers:
      - name: cs-container
        image: linuxserver/code-server:4.9.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: cs-cm
        volumeMounts:
          - name: workspace-vol
            mountPath: /config/workspace
---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  labels:
    app: codeserver
    name: cs-svc
  namespace: csns
spec:
  type: ClusterIP
  selector:
    name: cs-po
  ports:
  - port: 8443
    targetPort: 8443
--- 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: cs-ing
  labels:
    name: cs-ing
    app: codeserver
  namespace: csns
  annotations:
    nginx.ingress.kubernates.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  rules:
  - host: cs-146.190.193.110.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: cs-svc
            port: 
              number: 8443