apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-bear-deploy
  labels:
    name: dov-bear-deploy
  namespace: myns
spec:
  replicas: 3
  selector:
    matchLabels:
      name: dov-bear-po
  template:
    metadata:
      name: dov-bear-po
      labels:
        name: dov-bear-po
    spec:
      volumes: 
        - name: config-vol
          configMap:
            name: config-cm
        - name: tmp-vol
          emptyDir: {}
      containers:
      - name: dov-bear-container
        image: superalim/dov-bear:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: dov-bear
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: "3000"
        ports:
        - containerPort: 3000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
        volumeMounts:
        - name: config-vol
          mountPath: /app/config
          readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: dov-bear-svc
  labels:
    name: dov-bear-svc
  namespace: myns
spec:
  type: ClusterIP
  selector:
    name: dov-bear-po
    dept: dev
  ports:
  - port: 80
    targetPort: 3000
